name: fullstack101 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cibuild:
    runs-on: ubuntu-latest
  steps:
    - run: ls -al
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install
    - run: ls -al
  